### PR TITLE
Fix/upgrading ga4

### PR DESCRIPTION
**Pull request by rafayrty**
- Migrated the Old Universal Analytics Code to the New GA4.
- Removed ActiveUsersFourteenDayWidget as the New GA4 Property doesn't support the metric active14DayUsers

Any change or improvement is appreciated.

### CODE REVIEW

**Comment by Saifallak** [comment]
image

getting error overhere.

**Comment by Saifallak** [comment]
flare error https://flareapp.io/share/xmNlvwy7

**Comment by rafayrty** [comment]
i am unable to reproduce the error but try replacing it with:
```
            'result' => $analyticsData->last()['activeUsers'] ?? 0,
            'previous' => $analyticsData->first()['activeUsers'] ?? 0,
```

**Comment by Kmap-Holdings** [comment]
Used some of this code in my own project. Works well. Not too sure if the maintainer is still active on this. Has not been responsive for a while.

**Comment by bezhanSalleh** [comment]
fixes #28

**Pull request merged**
